const express = require('express');
const authRoutes = require('./authRoutes');
const researchRoutes = require('./researchRoutes');
const classRoutes = require('./classRoutes');
const instituteRoutes = require('./instituteRoutes');
// const courseRoutes = require('./courseRoutes');
const publicRoutes = require('./publicRoutes');
const crmRoutes = require('./crmRoutes');
const programRoutes = require('./programRoutes');
const partnerRoutes = require('./partnerRoutes');
const testimonialRoutes = require('./testimonialRoutes');
const paymentRoutes = require('./paymentRoutes');
const studentProfileRoutes = require('./studentProfileRoutes');
const eventRoutes = require('./eventRoutes');
const activityRoutes = require('./activityRoutes');
const mediaRoutes = require('./mediaRoutes');
const userRoutes = require('./userRoutes');
// const studyLanguageRoutes = require('./studyLanguageRoutes');
// const libraryRoutes = require('./libraryRoutes');
// const quizRoutes = require('./quizRoutes');
// const examRoutes = require('./examRoutes');
const liveClassRoutes = require('./liveClassRoutes');
const uploadRoutes = require('./uploadRoutes');
const videoRoutes = require('./videoRoutes');
// const sectionRoutes = require('./sectionRoutes');
// const enrollmentRoutes = require('./enrollmentRoutes');
const aiRoutes = require('./aiRoutes');
const settingRoutes = require('./settingRoutes');
const departmentRoutes = require('./departmentRoutes');
const internshipApplicationRoutes = require('./internshipApplicationRoutes');
const internshipRoutes = require('./internshipRoutes');
const taskRoutes = require('./taskRoutes');
const reportRoutes = require('./reportRoutes');
// const aiMockExamRoutes = require('./aiMockExamRoutes');
// const aiExamRoutes = require('./aiExamRoutes');
// const examSessionRoutes = require('./examSessionRoutes');
// const examAttemptRoutes = require('./examAttemptRoutes');

const router = express.Router();

router.use('/auth', authRoutes);
router.use('/classes', classRoutes);
router.use('/research', researchRoutes);
router.use('/institutes', instituteRoutes);
// router.use('/courses', courseRoutes);
router.use('/public', publicRoutes);
router.use('/crm', crmRoutes);
router.use('/programs', programRoutes);
router.use('/partners', partnerRoutes);
router.use('/testimonials', testimonialRoutes);
router.use('/payments', paymentRoutes);
router.use('/student-profiles', studentProfileRoutes);
router.use('/events', eventRoutes);
router.use('/activities', activityRoutes);
router.use('/media', mediaRoutes);
router.use('/users', userRoutes);
// router.use('/study-languages', studyLanguageRoutes);
// router.use('/library', libraryRoutes);
// router.use('/quizzes', quizRoutes);
// router.use('/exams', examRoutes);
router.use('/live-classes', liveClassRoutes);
router.use('/upload', uploadRoutes);
router.use('/videos', videoRoutes);
// router.use('/sections', sectionRoutes);
// router.use('/enrollments', enrollmentRoutes);
router.use('/ai', aiRoutes);
router.use('/settings', settingRoutes);
router.use('/departments', departmentRoutes);
router.use('/applications', internshipApplicationRoutes);
router.use('/internships', internshipRoutes);
router.use('/tasks', taskRoutes);
router.use('/reports', reportRoutes);
// router.use('/ai-mock-exams', aiMockExamRoutes);
// router.use('/ai-exams', aiExamRoutes);
// router.use('/exam-sessions', examSessionRoutes);
// router.use('/exam-attempts', examAttemptRoutes);

module.exports = router;
